B_HEADER
 FileSign ASSN FormVers 1.000 CreaSign MATS CreaVers 3.000
 FileMark DBRootFile
E_HEADER

B_DATA 
 B_DBASE ansoftvslinpar_magn 0 BlockSep B_ASNTAB 
  B_ASNTAB ansoftvslinpar_magn 1 BlockSep AssignTo PrvIndex 27 ParentDB ansoftvslinpar_magn 
   AssignTo Trace 27 
    Material copper 3 
   AssignTo Substrate 9 
    Material Substrate 2 
   AssignTo GND 18 
    Material copper 3 
   AssignTo background 0 
    Material vacuum 1 
  E_ASNTAB 
 E_DBASE 
E_DATA 
