# ------------------------------------------------------
# generated by builder.sce : Please do not edit this file
# see TEMPLATE makefile for Visual Studio
# see SCI/modules/dynamic_link/src/scripts/TEMPLATE_MAKEFILE.VC
# ------------------------------------------------------
SCIDIR = E:/SCILAB~1.0
SCIDIR1 = E:\SCILAB~1.0
# ------------------------------------------------------
# name of the dll to be built
LIBRARY = libwrite_tchstn
# ------------------------------------------------------
# list of files
FILES_SRC = write_tchstn.c
# ------------------------------------------------------
# list of objects file
OBJS = write_tchstn.obj
OBJS_WITH_PATH = Release/write_tchstn.obj
# ------------------------------------------------------
# added libraries
FORTRAN_RUNTIME_LIBRARIES = 
OTHERLIBS =  liberr_codes.lib
# ------------------------------------------------------
!include $(SCIDIR1)\modules\dynamic_link\src\scripts\Makefile.incl.mak
# ------------------------------------------------------
#CC = 
# ------------------------------------------------------
CFLAGS = $(CC_OPTIONS) -DFORDLL -IE:\scilab-5.2.0\contrib\SparamToolbox\src\c\ 
# ------------------------------------------------------
FFLAGS = $(FC_OPTIONS) -DFORDLL  
# ------------------------------------------------------
EXTRA_LDFLAGS = 
# ------------------------------------------------------
!include $(SCIDIR1)\modules\dynamic_link\src\scripts\Makedll.incl
# ------------------------------------------------------
