// This file is released into the public domain
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('Makelib.mak') <> [] then
  unix_s('nmake /Y /nologo /f Makelib.mak clean');
  mdelete('Makelib.mak');
end
// ------------------------------------------------------
if fileinfo('sparlib_c.dll') <> [] then
  mdelete('sparlib_c.dll');
end
// ------------------------------------------------------
if fileinfo('sparlib_c.c') <> [] then
  mdelete('sparlib_c.c');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
